Repository IncredibleHannes/TPF2-Timetables, pull requests merged in 2021-03, with the labels that each got.

#18 implemented suggested bugfix
  res/scripts/celmi/timetables/timetable.lua
Labels: bug

#5 Multi lang support
  res/config/game_script/timetable_gui.lua
  res/scripts/celmi/timetables/timetable_helper.lua
  strings.lua
Labels: enhancement

#8 Improve train stopping on big maps with much lines and vehicles
  res/config/game_script/timetable_gui.lua
  res/scripts/celmi/timetables/timetable.lua
  res/scripts/celmi/timetables/timetable_helper.lua
Labels: bug

#15 Refactore of the TimetableHelper, introduction of linter to build process
  .github/workflows/blank.yml
  .luacheckrc
  mod.lua
  res/config/game_script/timetable_gui.lua
  res/config/style_sheet/timetable_stylesheet.lua
  res/scripts/celmi/timetables/timetable.lua
  res/scripts/celmi/timetables/timetable_helper.lua
  strings.lua
  tests/main_tests.lua
  tests/timetable_helper_tests.lua
  tests/timetable_tests.lua
Labels: enhancement

#31 #3 random crashes when adding arr dep
  res/config/game_script/timetable_gui.lua
  strings.lua
Labels: bug

#28 Removes all game.interface calls
  res/scripts/celmi/timetables/timetable_helper.lua
Labels: enhancement

#33 fix unrestricted timestamp in getDifference
  res/scripts/celmi/timetables/timetable.lua
  tests/timetable_tests.lua
Labels: bug

#44 Release v1.1
  .github/workflows/blank.yml
  .luacheckrc
  README.md
  description.txt
  mod.lua
  res/config/game_script/timetable_gui.lua
  res/config/style_sheet/timetable_stylesheet.lua
  res/scripts/celmi/timetables/timetable.lua
  res/scripts/celmi/timetables/timetable_helper.lua
  strings.lua
  tests/main_tests.lua
  tests/timetable_helper_tests.lua
  tests/timetable_tests.lua
Labels: release

#65 Release v1.2
  .gitignore
  res/config/game_script/timetable_gui.lua
  res/scripts/celmi/timetables/timetable_helper.lua
  strings.lua
Labels: release

#72 removed direct indexing of getComponent as suggested in #50
  res/scripts/celmi/timetables/timetable_helper.lua
Labels: bug

#77 Grisu/feature 14 linecolors
  .luacheckrc
  res/config/style_sheet/timetable_colors.lua
  res/config/style_sheet/timetable_stylesheet.lua
  res/scripts/celmi/timetables/timetable_helper.lua
Labels: enhancement
